# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.16
# from Racc grammar file "".
#

require 'racc/parser.rb'
module RuboCop
  module AST
    class NodePattern
      class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    14,    15,    16,    20,    18,    17,    19,    10,    11,    12,
    59,    21,     4,    39,     5,    42,     6,     7,     8,    27,
    22,    55,    49,    65,    23,    60,    50,    50,    39,    57,
    14,    15,    16,    20,    18,    17,    19,    10,    11,    12,
   nil,    21,     4,   nil,     5,   nil,     6,     7,     8,    27,
    22,   nil,   nil,   -33,    14,    15,    16,    20,    18,    17,
    19,    10,    11,    12,   nil,    21,     4,   nil,     5,   nil,
     6,     7,     8,     9,    22,    14,    15,    16,    20,    18,
    17,    19,    10,    11,    12,   nil,    21,     4,   nil,     5,
   nil,     6,     7,     8,     9,    22,    14,    15,    16,    20,
    18,    17,    19,    10,    11,    12,   nil,    21,     4,   nil,
     5,   nil,     6,     7,     8,     9,    22,    14,    15,    16,
    20,    18,    17,    19,    10,    11,    12,   nil,    21,     4,
   nil,     5,   nil,     6,     7,     8,     9,    22,    14,    15,
    16,    20,    18,    17,    19,    10,    11,    12,   nil,    21,
     4,   nil,     5,   nil,     6,     7,     8,     9,    22,    14,
    15,    16,    20,    18,    17,    19,    10,    11,    12,   nil,
    21,     4,   nil,     5,   nil,     6,     7,     8,     9,    22,
    14,    15,    16,    20,    18,    17,    19,    10,    11,    12,
   nil,    21,     4,   nil,     5,   nil,     6,     7,     8,    27,
    22,    14,    15,    16,    20,    18,    17,    19,    10,    11,
    12,   nil,    21,     4,    43,     5,   nil,     6,     7,     8,
    27,    22,    14,    15,    16,    20,    18,    17,    19,    10,
    11,    12,   nil,    21,     4,   nil,     5,   nil,     6,     7,
     8,     9,    22,    14,    15,    16,    20,    18,    17,    19,
    10,    11,    12,   nil,    21,     4,   nil,     5,    51,     6,
     7,     8,     9,    22,    14,    15,    16,    20,    18,    17,
    19,    10,    11,    12,   nil,    21,     4,   nil,     5,   nil,
     6,     7,     8,     9,    22,    14,    15,    16,    20,    18,
    17,    19,    10,    11,    12,   nil,    21,     4,   nil,     5,
   nil,     6,     7,     8,     9,    22,    14,    15,    16,    20,
    18,    17,    19,    10,    11,    12,   nil,    21,     4,   nil,
     5,   nil,     6,     7,     8,     9,    22,    46,    47,    48,
    -1,    -1,    -1,    -2,    -2,    -2 ]

racc_action_check = [
    41,    41,    41,    41,    41,    41,    41,    41,    41,    41,
    53,    41,    41,    11,    41,    23,    41,    41,    41,    41,
    41,    41,    29,    61,     1,    53,    62,    29,    10,    41,
    58,    58,    58,    58,    58,    58,    58,    58,    58,    58,
   nil,    58,    58,   nil,    58,   nil,    58,    58,    58,    58,
    58,   nil,   nil,    58,     5,     5,     5,     5,     5,     5,
     5,     5,     5,     5,   nil,     5,     5,   nil,     5,   nil,
     5,     5,     5,     5,     5,     6,     6,     6,     6,     6,
     6,     6,     6,     6,     6,   nil,     6,     6,   nil,     6,
   nil,     6,     6,     6,     6,     6,     7,     7,     7,     7,
     7,     7,     7,     7,     7,     7,   nil,     7,     7,   nil,
     7,   nil,     7,     7,     7,     7,     7,     8,     8,     8,
     8,     8,     8,     8,     8,     8,     8,   nil,     8,     8,
   nil,     8,   nil,     8,     8,     8,     8,     8,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,   nil,     9,
     9,   nil,     9,   nil,     9,     9,     9,     9,     9,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,   nil,
     0,     0,   nil,     0,   nil,     0,     0,     0,     0,     0,
     4,     4,     4,     4,     4,     4,     4,     4,     4,     4,
   nil,     4,     4,   nil,     4,   nil,     4,     4,     4,     4,
     4,    26,    26,    26,    26,    26,    26,    26,    26,    26,
    26,   nil,    26,    26,    26,    26,   nil,    26,    26,    26,
    26,    26,    27,    27,    27,    27,    27,    27,    27,    27,
    27,    27,   nil,    27,    27,   nil,    27,   nil,    27,    27,
    27,    27,    27,    32,    32,    32,    32,    32,    32,    32,
    32,    32,    32,   nil,    32,    32,   nil,    32,    32,    32,
    32,    32,    32,    32,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,   nil,    39,    39,   nil,    39,   nil,
    39,    39,    39,    39,    39,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49,   nil,    49,    49,   nil,    49,
   nil,    49,    49,    49,    49,    49,    60,    60,    60,    60,
    60,    60,    60,    60,    60,    60,   nil,    60,    60,   nil,
    60,   nil,    60,    60,    60,    60,    60,    28,    28,    28,
    24,    24,    24,    25,    25,    25 ]

racc_action_pointer = [
   157,    24,   nil,   nil,   178,    52,    73,    94,   115,   136,
    16,     1,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    15,   304,   307,   199,   220,   301,    -2,
   nil,   nil,   241,   nil,   nil,   nil,   nil,   nil,   nil,   262,
   nil,    -2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   283,
   nil,   nil,   nil,    -5,   nil,   nil,   nil,   nil,    28,   nil,
   304,    -2,    -3,   nil,   nil,   nil ]

racc_action_default = [
   -46,   -46,    -1,    -2,   -30,   -46,   -46,   -46,   -46,   -46,
   -35,   -35,   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,
   -19,   -20,   -43,   -46,   -22,   -23,   -30,   -31,   -46,   -46,
   -26,   -41,   -46,   -39,    -5,    -6,    -7,    -8,    -9,   -46,
   -10,   -30,    66,    -3,   -42,   -24,   -27,   -28,   -29,   -46,
   -32,    -4,   -40,   -46,   -37,   -21,   -44,   -45,   -30,   -36,
   -46,   -46,   -46,   -34,   -38,   -25 ]

racc_goto_table = [
     1,    32,    63,    31,    24,    33,    34,    35,    36,    37,
    53,    25,    38,    40,    26,    41,    45,    62,    61,   nil,
   nil,   nil,   nil,   nil,   nil,    44,    24,    37,   nil,   nil,
   nil,   nil,    52,    25,   nil,   nil,   nil,   nil,   nil,    54,
    56,    24,   nil,   nil,   nil,    58,   nil,   nil,    25,    33,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    52,   nil,
    64 ]

racc_goto_check = [
     1,     5,    13,     9,     2,     1,     1,     1,     1,     1,
    14,     3,     6,     6,     4,     8,    10,    11,    12,   nil,
   nil,   nil,   nil,   nil,   nil,     9,     2,     1,   nil,   nil,
   nil,   nil,     1,     3,   nil,   nil,   nil,   nil,   nil,     1,
     9,     2,   nil,   nil,   nil,     5,   nil,   nil,     3,     1,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     1,   nil,
     1 ]

racc_goto_pointer = [
   nil,     0,     0,     7,    10,    -4,     2,   nil,    -7,    -1,
   -12,   -41,   -40,   -56,   -29 ]

racc_goto_default = [
   nil,    28,     2,     3,   nil,   nil,   nil,    13,   nil,   nil,
   nil,    29,   nil,    30,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 33, :_reduce_none,
  1, 33, :_reduce_2,
  3, 34, :_reduce_3,
  3, 34, :_reduce_4,
  2, 34, :_reduce_5,
  2, 34, :_reduce_6,
  2, 34, :_reduce_7,
  2, 34, :_reduce_8,
  2, 34, :_reduce_9,
  2, 34, :_reduce_10,
  1, 34, :_reduce_11,
  1, 34, :_reduce_none,
  1, 39, :_reduce_13,
  1, 39, :_reduce_14,
  1, 39, :_reduce_15,
  1, 39, :_reduce_16,
  1, 39, :_reduce_17,
  1, 39, :_reduce_18,
  1, 39, :_reduce_19,
  1, 39, :_reduce_20,
  3, 35, :_reduce_21,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  2, 41, :_reduce_24,
  5, 41, :_reduce_25,
  1, 41, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  0, 43, :_reduce_none,
  1, 43, :_reduce_none,
  2, 45, :_reduce_32,
  0, 44, :_reduce_none,
  1, 44, :_reduce_none,
  0, 38, :_reduce_none,
  3, 38, :_reduce_36,
  1, 46, :_reduce_37,
  3, 46, :_reduce_38,
  1, 37, :_reduce_39,
  2, 37, :_reduce_40,
  1, 36, :_reduce_41,
  2, 36, :_reduce_42,
  0, 40, :_reduce_43,
  2, 40, :_reduce_44,
  2, 40, :_reduce_45 ]

racc_reduce_n = 46

racc_shift_n = 66

racc_token_table = {
  false => 0,
  :error => 1,
  :tSYMBOL => 2,
  :tNUMBER => 3,
  :tSTRING => 4,
  :tWILDCARD => 5,
  :tPARAM_NAMED => 6,
  :tPARAM_CONST => 7,
  :tPARAM_NUMBER => 8,
  :tFUNCTION_CALL => 9,
  :tPREDICATE => 10,
  :tNODE_TYPE => 11,
  :tARG_LIST => 12,
  :tUNIFY => 13,
  "(" => 14,
  ")" => 15,
  "[" => 16,
  "]" => 17,
  "!" => 18,
  "^" => 19,
  "`" => 20,
  "$" => 21,
  "{" => 22,
  "}" => 23,
  "<" => 24,
  ">" => 25,
  "?" => 26,
  "*" => 27,
  "+" => 28,
  "..." => 29,
  "," => 30,
  "|" => 31 }

racc_nt_base = 32

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "tSYMBOL",
  "tNUMBER",
  "tSTRING",
  "tWILDCARD",
  "tPARAM_NAMED",
  "tPARAM_CONST",
  "tPARAM_NUMBER",
  "tFUNCTION_CALL",
  "tPREDICATE",
  "tNODE_TYPE",
  "tARG_LIST",
  "tUNIFY",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"!\"",
  "\"^\"",
  "\"`\"",
  "\"$\"",
  "\"{\"",
  "\"}\"",
  "\"<\"",
  "\">\"",
  "\"?\"",
  "\"*\"",
  "\"+\"",
  "\"...\"",
  "\",\"",
  "\"|\"",
  "$start",
  "node_pattern",
  "node_pattern_no_union",
  "union",
  "variadic_pattern_list",
  "node_pattern_list",
  "args",
  "atom",
  "separated_variadic_patterns",
  "variadic_pattern",
  "repetition",
  "opt_capture",
  "opt_rest",
  "rest",
  "arg_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

def _reduce_2(val, _values)
 enforce_unary(val[0])
end

def _reduce_3(val, _values)
 emit_list :sequence, *val
end

def _reduce_4(val, _values)
 emit_list :intersection, *val
end

def _reduce_5(val, _values)
 emit_unary_op :negation, *val
end

def _reduce_6(val, _values)
 emit_unary_op :ascend, *val
end

def _reduce_7(val, _values)
 emit_unary_op :descend, *val
end

def _reduce_8(val, _values)
 emit_capture(*val)
end

def _reduce_9(val, _values)
 emit_call :function_call, *val
end

def _reduce_10(val, _values)
 emit_call :predicate, *val
end

def _reduce_11(val, _values)
 emit_call :node_type, *val
end

# reduce 12 omitted

def _reduce_13(val, _values)
 emit_atom :symbol, *val
end

def _reduce_14(val, _values)
 emit_atom :number, *val
end

def _reduce_15(val, _values)
 emit_atom :string, *val
end

def _reduce_16(val, _values)
 emit_atom :const, *val
end

def _reduce_17(val, _values)
 emit_atom :named_parameter, *val
end

def _reduce_18(val, _values)
 emit_atom :positional_parameter, *val
end

def _reduce_19(val, _values)
 emit_atom :wildcard, *val
end

def _reduce_20(val, _values)
 emit_atom :unify, *val
end

def _reduce_21(val, _values)
 emit_union(*val)
end

# reduce 22 omitted

# reduce 23 omitted

def _reduce_24(val, _values)
        main, repeat_t = val
        emit_unary_op(:repetition, repeat_t, main, repeat_t)

end

def _reduce_25(val, _values)
        opt_capture, bracket, node_pattern_list, opt_rest, close_bracket = val
        node_pattern_list << opt_rest if opt_rest
        main = emit_list :any_order, bracket, node_pattern_list, close_bracket
        emit_capture(opt_capture, main)

end

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

def _reduce_32(val, _values)
 emit_capture(val[0], emit_atom(:rest, val[1]))
end

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

def _reduce_36(val, _values)
 val
end

def _reduce_37(val, _values)
 val
end

def _reduce_38(val, _values)
 val[0] << val[2]
end

def _reduce_39(val, _values)
 val
end

def _reduce_40(val, _values)
 val[0] << val[1]
end

def _reduce_41(val, _values)
 val
end

def _reduce_42(val, _values)
 val[0] << val[1]
end

def _reduce_43(val, _values)
 [[]]
end

def _reduce_44(val, _values)
 val[0].last << val[1]; val[0]
end

def _reduce_45(val, _values)
 val[0] << []
end

def _reduce_none(val, _values)
  val[0]
end

      end   # class Parser
    end   # class NodePattern
  end   # module AST
end   # module RuboCop
